update hawk and misc.awk

diff --git a/scripts/hawk b/scripts/hawk
--- a/scripts/hawk
+++ b/scripts/hawk
@@ -8,17 +8,13 @@ not(){ if eval "$@"; then return 1; else return 0; fi; }
 newlines(){ awk '{for(i=1; i<=NF;i++)print $i}' "$@"; }
 parse(){ awk "BEGIN{print $@}" </dev/null; }
 
-TestGawk(){ echo hello | gawk '{++array[$1][$1]}' || die "Upgrade to a [g]awk that supports multi-dimensional arrays"; }
-TestGawk
-
 # generally useful Variables
 NL='
 '
 TAB='	'
 
 # Temporary Filename + Directory (both, you can use either, note they'll have different random stuff in the XXXXXX part)
-TMP=`mktemp /tmp/hawk.XXXXXX`
- trap "/bin/rm -rf $TMP; exit" 0 1 2 3 15 # call trap "" N to remove the trap for signal N
+TMPDIR=`mktemp -d /tmp/hawk.XXXXXX`
 
 DIR="`dirname $0`"
 FIELD_SEP=" " # space
@@ -40,7 +36,7 @@ done
 PROG="$1"
 shift
 
-echo "`cat "$DIR/misc.awk"`$PROG" > $TMP
+echo "`cat "$DIR/misc.awk"`$PROG" > $TMPDIR/PROG
 
 AWK=`(which ${PROFILE}gawk4 || which ${PROFILE}gawk) 2>/dev/null | head -1 | sed 's/\*//g'`
 if [ -x "$AWK" ] && $AWK --version 2>/dev/null | grep 'GNU Awk [45]\.' >/dev/null; then
@@ -50,7 +46,8 @@ else
 fi
 #echo '$AWK='"$AWK $PROF_OUT" >&2
 
-if $AWK $PROF_OUT -F "$FIELD_SEP" -f "$TMP" "$@"; then : # do nothing, just exit
+if $AWK $PROF_OUT -F "$FIELD_SEP" -f "$TMPDIR/PROG" "$@"; then : # do nothing, just exit
+    trap "/bin/rm -rf $TMPDIR; exit" 0 1 2 3 15
 else
     STATUS=$?
     [ $STATUS -le 3 ] && exit $STATUS
@@ -62,7 +59,8 @@ else
     else # kill -l has the format of space-separated "HUP INT QUIT", etc...
 	kill -l | newlines | grep -v IOT | nl   # but note IOT is a duplicate of TRAP--both are signal 6
     fi | head -20 | egrep -i "$IGNORE" | awk '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
-    echo "'$AWK $PROF_OUT' failed with status $STATUS program file is in file $TMP" >&2
-    trap "" 0 1 2 3 15 # do not remove file
+    ( echo "'$AWK $PROF_OUT' failed with status $STATUS; files in $TMPDIR; working directory was"
+	pwd; echo "filenames were"; for i in "$@"; do echo "$i"; done) >&2
+    #trap "" 0 1 2 3 15 # do not remove file
     exit $STATUS
 fi
