Fixed png output line in remove stars py3 file as the mode needed to be specified... imageio couldn't automatically determine it so we had to specify grayscale with alpha. Also updated a call to ls to be find * for when there are too many files for ls to check (arg list too long).

diff --git a/scripts/SpArcFiRe b/scripts/SpArcFiRe
--- a/scripts/SpArcFiRe
+++ b/scripts/SpArcFiRe
@@ -185,7 +185,7 @@ for i in $sfDir/*; do
     fi
 done
 
-ls $pngDir/*.png >/dev/null || die "can't find any png images in $pngDir;
+find $pngDir -type f -name '*.png' >/dev/null || die "can't find any png images in $pngDir;
 note that you must include an inDir (and it must exist) even if you start with PNG images."
 
 if "$WEB"; then  # don't allow huge images
